### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by DiegoLZZ** [AndASM/ANMSMEMSPC#2]
ANMSMEMSPC (v0.0.3): Andy's NMS Mod Enabler for the Microsoft Store / Xbox GamePass PC edition.
Nexus Mods: https://www.nexusmods.com/nomanssky/mods/1751 
Source Code: https://github.com/AndASM/ANMSMEMSPC 
License: GPL-3.0-only

Finding No Man's Sky Installation...
Error!
Please check https://github.com/AndASM/ANMSMEMSPC/issues for this issue.
If it hasn't been reported, please click the New Issue button and report it.
Please include the error log available here:
D:\New folder\ErrorLog.txt

Important technical details:
System.Exception: Illegal operation attempted on a registry key that has been marked for deletion.

Illegal operation attempted on a registry key that has been marked for deletion.

   at Windows.Management.Deployment.PackageManager.FindPackagesForUser(String userSecurityId)
   at AndysNMSWinStoreModFix.NmsPackage..ctor()
   at AndysNMSWinStoreModFix.Program.DoEverything()
   at AndysNMSWinStoreModFix.Program.Main(String[] args)

**Comment by AndASM** [comment]
Hmm, that's a strange one. A few troubleshooting steps to try since a new version of the game was released today:
1. Open the Microsoft Store app
2. In the top right click the ellipsis/hamburger button (three dots: ...)
3. Click the `Get updates` button
4. Wait until the spinner is gone, the button turns blue again, and there are no further updates
  - If you click `Get updates` again you should get a `You're good to go` message
5. Find No Man's Sky on that screen under the `Recent activity` header
6. The version on No Man's Sky should be 3.5.64966.0
  - 3.5 is the important part
7. Restart your computer
8. Try my program again

Let me know how that goes, if it works or not.

**Comment by AndASM** [comment]
Closed as per discussion here: https://www.nexusmods.com/nomanssky/mods/1751?tab=bugs&issue_id=485230
Path issue fixed and will be published with v0.0.5
