### ISSUE TITLE
System.IO.FileNotFoundException: The system cannot find the file specified.

### ISSUE THREAD

**Issue by TeHammer** [AndASM/ANMSMEMSPC#3]
Installed the program and ran it and was met with this error:
System.IO.FileNotFoundException: The system cannot find the file specified.

An item cannot be found with the specified name (Local\Microsoft\WritablePackageRoot\GAMEDATA\PCBANKS).
   at AndysNMSWinStoreModFix.NmsPackage.get_PcBanksFolder()
   at AndysNMSWinStoreModFix.Program.DoEverything()
   at AndysNMSWinStoreModFix.Program.Main(String[] args)

**Comment by AndASM** [comment]
Sorry for the slow reply. I haven't played the game for a while.

Two possibilities off the top of my head, if I'm remembering correctly:

1. Had you run the game since it was installed, reinstalled, reset, or updated? If not, try running the game first, load fully in until you can control your character. Then quit properly through the menu.
2. Go to the releases and grab the oldest one. The old version worked through a completely different mechanism. If the new one doesn't work the old one might.


Let me know how it goes! If I have time I'll try to update the app based on the results.

**Comment by TeHammer** [comment]
I found that out shortly after this I just wanted to leave it up for other people just incase they haven't ran the game since the update but thanks for the reply.

**Comment by AndASM** [comment]
Hey, out of curiosity, which fix worked for you? Running the game first, or using the old version?

If people are still using this, and it's still working, I should probably update it!

**Comment by TeHammer** [comment]
Running the game first and it still works with the newest update
